[package]
name = "wasiruntime-rs"
version = "0.1.0"
authors = ["papamitra <papamitra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
thiserror = "1.0"